version: '3'
vars:
  name: ""
tasks:
  archive:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - sh archive.sh

  xcframework:
    desc: Create all .xcframeworks from archives
    cmds:
      - mkdir -p ./Framework
      - sh xcframework.sh MaterialComponents
      - sh xcframework.sh MDFInternationalization
      - sh xcframework.sh MDFTextAccessibility
      - sh xcframework.sh XLPagerTabStrip
      - sh xcframework.sh IQKeyboardManagerSwift
      - sh xcframework.sh Cluster

  zip:
    desc: Zip all.xcframeworks
    cmds:
      - sh zip.sh MaterialComponents
      - sh zip.sh MDFInternationalization
      - sh zip.sh MDFTextAccessibility
      - sh zip.sh XLPagerTabStrip
      - sh zip.sh IQKeyboardManagerSwift
      - sh zip.sh Cluster
      - checksum
  
  checksum:
    desc: Checksum all.xcframeworks
    cmds:
      - sh checksum.sh MaterialComponents
      - sh checksum.sh MDFInternationalization
      - sh checksum.sh MDFTextAccessibility
      - sh checksum.sh XLPagerTabStrip
      - sh checksum.sh IQKeyboardManagerSwift
      - sh checksum.sh XLPagerTabStrip
      - sh checksum.sh Cluster

  build:all:
    desc: Build all.xcframeworks
    cmds:
      - archive
      - xcframework
      - zip
  
  # task build:man name=MyFramework
  build:man:
    desc: Build {{.name}}.xcframeworks
    cmds:
      - sh archive.sh
      - sh xcframework.sh {{.name}}
      - sh zip.sh {{.name}}
      - sh checksum.sh {{.name}}